name: hormiga
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  google_fonts: ^6.0.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  geocoding: ^2.0.5
  flutter_local_notifications: ^19.4.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Hormiga.png
    - assets/images/Avatar.png
    - assets/images/sample1.png
    - assets/images/cortez.jpg
    - assets/images/Alcaldia.jpg
    - assets/images/colapso.jpg
    - assets/images/JINOTEPE.png
    - assets/images/SINAPRED.jpg
    - assets/images/fondo.png
    - assets/images/INCENDIO.png
    - assets/images/HURACAN.png
    - assets/images/SISMO.png
    - assets/images/DESLAVE.png
    - assets/images/LogoE.png
